#ifndef PATIENT_MONITOR_H_
#define PATIENT_MONITOR_H_
#include "Platform.h"
#define PM_SCREEN_WIDTH 1280
#define PM_SCREEN_HEIGHT 800
enum PatientMonitorTag {
    PM_TAG_NONE = 0, PM_TAG_SILENCE, PM_TAG_ALARMS_OFF, PM_TAG_PREVIOUS,
    PM_TAG_NBP, PM_TAG_STOP_ALL, PM_TAG_REPEAT, PM_TAG_SIZE, PM_TAG_ZERO,
    PM_TAG_VALUES, PM_TAG_RECORD, PM_TAG_TREND, PM_TAG_NEXT, PM_TAG_SETUP, PM_TAG_MAIN
};
#endif
